import java.awt.Image;

public class Luigi extends Mario {
	//ALL CHARACTERS (except for mario) need to extend Mario
	public Luigi(Image smallMarioLeftImage, Image smallMarioRightImage, Image smallMarioLeftWalkingImage,
			Image smallMarioRightWalkingImage, Image smallMarioLeftJumpingImage, Image smallMarioRightJumpingImage,
			Image marioDeadImage, Image bigMarioLeftImage, Image bigMarioRightImage, Image bigMarioLeftWalkingImage,
			Image bigMarioRightWalkingImage, Image bigMarioLeftJumpingImage, Image bigMarioRightJumpingImage,
			Image bigMarioLeftFireImage, Image bigMarioRightFireImage, Image bigMarioLeftWalkingFireImage,
			Image bigMarioRightWalkingFireImage, Image bigMarioLeftJumpingFireImage,
			Image bigMarioRightJumpingFireImage, Image bigMarioLeftJumpingDownImage,
			Image bigMarioRightJumpingDownImage, Image bigMarioLeftJumpingDownFireImage,
			Image bigMarioRightJumpingDownFireImage, Image bigMarioLeftCrouchingImage,
			Image bigMarioRightCrouchingImage, Image bigMarioLeftCrouchingFireImage,
			Image bigMarioRightCrouchingFireImage, Image bigMarioLeftFireShooting1Image,
			Image bigMarioLeftFireShooting2Image, Image bigMarioRightFireShooting1Image,
			Image bigMarioRightFireShooting2Image, Image bigMarioLeftJumpingFireShooting1Image,
			Image bigMarioLeftJumpingFireShooting2Image, Image bigMarioLeftJumpingFireShooting3Image,
			Image bigMarioRightJumpingFireShooting1Image, Image bigMarioRightJumpingFireShooting2Image,
			Image bigMarioRightJumpingFireShooting3Image, Image bigMarioLeftCatImage, Image bigMarioRightCatImage,
			Image bigMarioLeftWakingCatImage, Image bigMarioRightWalkingCatImage, Image bigMarioLeftJumpingCatImage,
			Image bigMarioRightJumpingCatImage, Image bigMarioRightJumpingDownCatImage,
			Image bigMarioLeftJumpingDownCatImage, Image bigMarioLeftCrouchingCatImage,
			Image bigMarioRightCrouchingCatImage, Image bigMarioLeftJumpingCatTail1Image,
			Image bigMarioRightJumpingCatTail1Image, Image bigMarioLeftJumpingCatTail2Image,
			Image bigMarioRightJumpingCatTail2Image, Image bigMarioCatTail1Image, Image bigMarioLeftCatTail2Image,
			Image bigMarioRightCatTail2Image, Image bigMarioCatTail3Image, 
			Image tanookiMarioLeftCatImage, Image tanookiMarioRightCatImage, Image tanookiMarioLeftWakingCatImage, Image tanookiMarioRightWalkingCatImage,
			Image tanookiMarioLeftJumpingCatImage, Image tanookiMarioRightJumpingCatImage, Image tanookiMarioRightJumpingDownCatImage,
			Image tanookiMarioLeftJumpingDownCatImage, Image tanookiMarioLeftCrouchingCatImage, Image tanookiMarioRightCrouchingCatImage,
			Image tanookiMarioLeftJumpingCatTail1Image, Image tanookiMarioRightJumpingCatTal1Image, Image tanookiMarioLeftJumpingCatTail2Image,
			Image tanookiMarioRightJumpingCatTail2Image,
			Image tanookiMarioCatTail1Image, Image tanookiMarioLeftCatTail2Image,
			Image tanookiMarioRightCatTail2Image, Image tanookiMarioCatTail3Image,
			Image smallMarioPipeImage,
			Image bigMarioPipeImage, Image fireMarioPipeImage, CHARACTER character) {
		super(smallMarioLeftImage, smallMarioRightImage, smallMarioLeftWalkingImage, smallMarioRightWalkingImage,
				smallMarioLeftJumpingImage, smallMarioRightJumpingImage, marioDeadImage, bigMarioLeftImage, bigMarioRightImage,
				bigMarioLeftWalkingImage, bigMarioRightWalkingImage, bigMarioLeftJumpingImage, bigMarioRightJumpingImage,
				bigMarioLeftFireImage, bigMarioRightFireImage, bigMarioLeftWalkingFireImage, bigMarioRightWalkingFireImage,
				bigMarioLeftJumpingFireImage, bigMarioRightJumpingFireImage, bigMarioLeftJumpingDownImage,
				bigMarioRightJumpingDownImage, bigMarioLeftJumpingDownFireImage, bigMarioRightJumpingDownFireImage,
				bigMarioLeftCrouchingImage, bigMarioRightCrouchingImage, bigMarioLeftCrouchingFireImage,
				bigMarioRightCrouchingFireImage, bigMarioLeftFireShooting1Image, bigMarioLeftFireShooting2Image,
				bigMarioRightFireShooting1Image, bigMarioRightFireShooting2Image, bigMarioLeftJumpingFireShooting1Image,
				bigMarioLeftJumpingFireShooting2Image, bigMarioLeftJumpingFireShooting3Image,
				bigMarioRightJumpingFireShooting1Image, bigMarioRightJumpingFireShooting2Image,
				bigMarioRightJumpingFireShooting3Image, bigMarioLeftCatImage, bigMarioRightCatImage, bigMarioLeftWakingCatImage,
				bigMarioRightWalkingCatImage, bigMarioLeftJumpingCatImage, bigMarioRightJumpingCatImage,
				bigMarioRightJumpingDownCatImage, bigMarioLeftJumpingDownCatImage, bigMarioLeftCrouchingCatImage,
				bigMarioRightCrouchingCatImage, bigMarioLeftJumpingCatTail1Image, bigMarioRightJumpingCatTail1Image,
				bigMarioLeftJumpingCatTail2Image, bigMarioRightJumpingCatTail2Image, bigMarioCatTail1Image,
				bigMarioLeftCatTail2Image, bigMarioRightCatTail2Image, bigMarioCatTail3Image, 
				tanookiMarioLeftCatImage, tanookiMarioRightCatImage, tanookiMarioLeftWakingCatImage, tanookiMarioRightWalkingCatImage,
				tanookiMarioLeftJumpingCatImage, tanookiMarioRightJumpingCatImage, tanookiMarioRightJumpingDownCatImage,
				tanookiMarioLeftJumpingDownCatImage, tanookiMarioLeftCrouchingCatImage, tanookiMarioRightCrouchingCatImage,
				tanookiMarioLeftJumpingCatTail1Image, tanookiMarioRightJumpingCatTal1Image, tanookiMarioLeftJumpingCatTail2Image,
				tanookiMarioRightJumpingCatTail2Image,
				tanookiMarioCatTail1Image, tanookiMarioLeftCatTail2Image,
				tanookiMarioRightCatTail2Image, tanookiMarioCatTail3Image,
				smallMarioPipeImage,
				bigMarioPipeImage, fireMarioPipeImage, character);
	}
}