import java.awt.Image;

public final class Luigi extends Mario {
	//ALL CHARACTERS (except for mario) need to extend Mario
	public Luigi(MyImage smallMarioLeftImage, MyImage smallMarioRightImage, MyImage smallMarioLeftWalkingImage,
			MyImage smallMarioRightWalkingImage, MyImage smallMarioLeftJumpingImage, MyImage smallMarioRightJumpingImage,
			MyImage marioDeadImage, MyImage bigMarioLeftImage, MyImage bigMarioRightImage, MyImage bigMarioLeftWalkingImage,
			MyImage bigMarioRightWalkingImage, MyImage bigMarioLeftJumpingImage, MyImage bigMarioRightJumpingImage,
			MyImage bigMarioLeftFireImage, MyImage bigMarioRightFireImage, MyImage bigMarioLeftWalkingFireImage,
			MyImage bigMarioRightWalkingFireImage, MyImage bigMarioLeftJumpingFireImage,
			MyImage bigMarioRightJumpingFireImage, MyImage bigMarioLeftJumpingDownImage,
			MyImage bigMarioRightJumpingDownImage, MyImage bigMarioLeftJumpingDownFireImage,
			MyImage bigMarioRightJumpingDownFireImage, MyImage bigMarioLeftCrouchingImage,
			MyImage bigMarioRightCrouchingImage, MyImage bigMarioLeftCrouchingFireImage,
			MyImage bigMarioRightCrouchingFireImage, MyImage bigMarioLeftFireShooting1Image,
			MyImage bigMarioLeftFireShooting2Image, MyImage bigMarioRightFireShooting1Image,
			MyImage bigMarioRightFireShooting2Image, MyImage bigMarioLeftJumpingFireShooting1Image,
			MyImage bigMarioLeftJumpingFireShooting2Image, MyImage bigMarioLeftJumpingFireShooting3Image,
			MyImage bigMarioRightJumpingFireShooting1Image, MyImage bigMarioRightJumpingFireShooting2Image,
			MyImage bigMarioRightJumpingFireShooting3Image, MyImage bigMarioLeftCatImage, MyImage bigMarioRightCatImage,
			MyImage bigMarioLeftWakingCatImage, MyImage bigMarioRightWalkingCatImage, MyImage bigMarioLeftJumpingCatImage,
			MyImage bigMarioRightJumpingCatImage, MyImage bigMarioRightJumpingDownCatImage,
			MyImage bigMarioLeftJumpingDownCatImage, MyImage bigMarioLeftCrouchingCatImage,
			MyImage bigMarioRightCrouchingCatImage, MyImage bigMarioLeftJumpingCatTail1Image,
			MyImage bigMarioRightJumpingCatTail1Image, MyImage bigMarioLeftJumpingCatTail2Image,
			MyImage bigMarioRightJumpingCatTail2Image, MyImage bigMarioCatTail1Image, MyImage bigMarioLeftCatTail2Image,
			MyImage bigMarioRightCatTail2Image, MyImage bigMarioCatTail3Image, 
			MyImage tanookiMarioLeftCatImage, MyImage tanookiMarioRightCatImage, MyImage tanookiMarioLeftWakingCatImage, MyImage tanookiMarioRightWalkingCatImage,
			MyImage tanookiMarioLeftJumpingCatImage, MyImage tanookiMarioRightJumpingCatImage, MyImage tanookiMarioRightJumpingDownCatImage,
			MyImage tanookiMarioLeftJumpingDownCatImage, MyImage tanookiMarioLeftCrouchingCatImage, MyImage tanookiMarioRightCrouchingCatImage,
			MyImage tanookiMarioLeftJumpingCatTail1Image, MyImage tanookiMarioRightJumpingCatTal1Image, MyImage tanookiMarioLeftJumpingCatTail2Image,
			MyImage tanookiMarioRightJumpingCatTail2Image,
			MyImage tanookiMarioCatTail1Image, MyImage tanookiMarioLeftCatTail2Image,
			MyImage tanookiMarioRightCatTail2Image, MyImage tanookiMarioCatTail3Image,
			MyImage smallMarioPipeImage,
			MyImage bigMarioPipeImage, MyImage fireMarioPipeImage,
			
			MyImage timedilatingsmallMarioLeftImage,
			MyImage timedilatingbigMarioLeftJumpingImage,
			MyImage timedilatingsmallMarioLeftWalkingImage,
			MyImage timedilatingbigMarioRightWalkingImage,
			MyImage timedilatingsmallMarioRightJumpingImage,
			MyImage timedilatingsmallMarioRightImage,
			MyImage timedilatingbigMarioRightCrouchingImage,
			MyImage timedilatingbigMarioLeftWalkingImage,
			MyImage timedilatingbigMarioPipe,
			MyImage timedilatingbigMarioLeftImage,
			MyImage timedilatingsmallMarioLeftJumpingImage,
			MyImage timedilatingbigMarioLeftJumpingDownImage,
			MyImage timedilatingsmallMarioRightWalkingImage,
			MyImage timedilatingbigMarioRightJumpingImage,
			MyImage timedilatingbigMarioRightImage,
			MyImage timedilatingsmallMarioPipe,
			MyImage timedilatingbigMarioLeftCrouchingImage,
			MyImage timedilatingbigMarioRightJumpingDownImage,
			CHARACTER character) {
		super(smallMarioLeftImage, smallMarioRightImage, smallMarioLeftWalkingImage, smallMarioRightWalkingImage,
				smallMarioLeftJumpingImage, smallMarioRightJumpingImage, marioDeadImage, bigMarioLeftImage, bigMarioRightImage,
				bigMarioLeftWalkingImage, bigMarioRightWalkingImage, bigMarioLeftJumpingImage, bigMarioRightJumpingImage,
				bigMarioLeftFireImage, bigMarioRightFireImage, bigMarioLeftWalkingFireImage, bigMarioRightWalkingFireImage,
				bigMarioLeftJumpingFireImage, bigMarioRightJumpingFireImage, bigMarioLeftJumpingDownImage,
				bigMarioRightJumpingDownImage, bigMarioLeftJumpingDownFireImage, bigMarioRightJumpingDownFireImage,
				bigMarioLeftCrouchingImage, bigMarioRightCrouchingImage, bigMarioLeftCrouchingFireImage,
				bigMarioRightCrouchingFireImage, bigMarioLeftFireShooting1Image, bigMarioLeftFireShooting2Image,
				bigMarioRightFireShooting1Image, bigMarioRightFireShooting2Image, bigMarioLeftJumpingFireShooting1Image,
				bigMarioLeftJumpingFireShooting2Image, bigMarioLeftJumpingFireShooting3Image,
				bigMarioRightJumpingFireShooting1Image, bigMarioRightJumpingFireShooting2Image,
				bigMarioRightJumpingFireShooting3Image, bigMarioLeftCatImage, bigMarioRightCatImage, bigMarioLeftWakingCatImage,
				bigMarioRightWalkingCatImage, bigMarioLeftJumpingCatImage, bigMarioRightJumpingCatImage,
				bigMarioRightJumpingDownCatImage, bigMarioLeftJumpingDownCatImage, bigMarioLeftCrouchingCatImage,
				bigMarioRightCrouchingCatImage, bigMarioLeftJumpingCatTail1Image, bigMarioRightJumpingCatTail1Image,
				bigMarioLeftJumpingCatTail2Image, bigMarioRightJumpingCatTail2Image, bigMarioCatTail1Image,
				bigMarioLeftCatTail2Image, bigMarioRightCatTail2Image, bigMarioCatTail3Image, 
				tanookiMarioLeftCatImage, tanookiMarioRightCatImage, tanookiMarioLeftWakingCatImage, tanookiMarioRightWalkingCatImage,
				tanookiMarioLeftJumpingCatImage, tanookiMarioRightJumpingCatImage, tanookiMarioRightJumpingDownCatImage,
				tanookiMarioLeftJumpingDownCatImage, tanookiMarioLeftCrouchingCatImage, tanookiMarioRightCrouchingCatImage,
				tanookiMarioLeftJumpingCatTail1Image, tanookiMarioRightJumpingCatTal1Image, tanookiMarioLeftJumpingCatTail2Image,
				tanookiMarioRightJumpingCatTail2Image,
				tanookiMarioCatTail1Image, tanookiMarioLeftCatTail2Image,
				tanookiMarioRightCatTail2Image, tanookiMarioCatTail3Image,
				smallMarioPipeImage,
				bigMarioPipeImage, fireMarioPipeImage,
				timedilatingsmallMarioLeftImage,
				timedilatingbigMarioLeftJumpingImage,
				timedilatingsmallMarioLeftWalkingImage,
				timedilatingbigMarioRightWalkingImage,
				timedilatingsmallMarioRightJumpingImage,
				timedilatingsmallMarioRightImage,
				timedilatingbigMarioRightCrouchingImage,
				timedilatingbigMarioLeftWalkingImage,
				timedilatingbigMarioPipe,
				timedilatingbigMarioLeftImage,
				timedilatingsmallMarioLeftJumpingImage,
				timedilatingbigMarioLeftJumpingDownImage,
				timedilatingsmallMarioRightWalkingImage,
				timedilatingbigMarioRightJumpingImage,
				timedilatingbigMarioRightImage,
				timedilatingsmallMarioPipe,
				timedilatingbigMarioLeftCrouchingImage,
				timedilatingbigMarioRightJumpingDownImage,
				character);
	}
}